import { afterEach,describe,expect,it,vi } from "vitest";import { ApiError,tokenStorage } from "../../../infrastructure/apiClient";import { loadMemberHome,mapMemberHomePayload,memberHomeEndpoint } from "./memberHomeApi";
const explore=[{actionId:"public-benefit-club",label:"公益俱乐部",href:"?category=公益俱乐部"},{actionId:"self-created-club",label:"自建俱乐部",href:"?category=自建俱乐部"},{actionId:"family-club",label:"家庭俱乐部",href:"?category=家庭俱乐部"},{actionId:"club-federation",label:"俱乐部友联体",href:"?category=俱乐部友联体"}];
const payload={display_name:"合成会员",joined_club_count:1,pending_task_count:1,unread_count:0,clubs:[{club_id:"c1",name:"合成俱乐部",kind:"自建俱乐部",member_role:"成员",status:"正常",target:"/clubs/c1"}],tasks:[{task_id:"t1",title:"查看申请",context:"待处理",target:"/tasks/t1"}],activities:[],feed:[]};
afterEach(()=>{vi.restoreAllMocks();tokenStorage.clear()});
describe("memberHomeApi",()=>{
 it("maps a strict payload",()=>{const m=mapMemberHomePayload(payload,explore);expect(m.state).toBe("ready");expect(m.clubs?.[0].clubId).toBe("c1");expect(m.explore).toEqual(explore)});
 it.each([[{},"CMH_CONTRACT_INVALID"],[{...payload,clubs:null},"CMH_CONTRACT_INVALID"],[{...payload,joined_club_count:-1},"CMH_CONTRACT_INVALID"],[{...payload,clubs:[{...payload.clubs[0],kind:"友联体"}]},"CMH_CONTRACT_INVALID"]])("fails malformed data closed",(data,code)=>{try{mapMemberHomePayload(data,explore);throw new Error("expected") }catch(e){expect(e).toBeInstanceOf(ApiError);expect((e as ApiError).code).toBe(code)}});
 it("uses one authenticated strict endpoint",async()=>{tokenStorage.set("synthetic-token");const f=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({success:true,data:payload}),{status:200,headers:{"Content-Type":"application/json"}}));await loadMemberHome(explore);expect(f).toHaveBeenCalledTimes(1);const [url,init]=f.mock.calls[0];expect(url).toBe(memberHomeEndpoint);expect(new Headers(init?.headers).get("Authorization")).toBe("Bearer synthetic-token")});
 it("rejects a legacy non-envelope response",async()=>{tokenStorage.set("synthetic-token");vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify(payload),{status:200,headers:{"Content-Type":"application/json"}}));await expect(loadMemberHome(explore)).rejects.toMatchObject({code:"INVALID_API_ENVELOPE"})});
 it("never falls back to mock or empty arrays",()=>{expect(loadMemberHome.toString()).not.toMatch(/catch|mock|return\s*\[\]/i)});
});
